language: cpp
os:
  - linux
  - osx
before_install:
  - wget -O ~/vicr12345.gpg.key https://vicr123.com/repo/apt/vicr12345.gpg.key
  - sudo apt-key add ~/vicr12345.gpg.key
  - sudo add-apt-repository 'deb https://vicr123.com/repo/apt/ubuntu bionic main'
  - sudo apt-get update -qq
  - sudo apt-get install qt5-qmake libqt5x11extras5-dev qt5-default
script:
  - ./travis.sh
after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh theSlate*.AppImage*

compiler:
  - gcc
dist: xenial

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/